apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-mobile-banking
  name: mb-mjbl-account
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mb-mjbl-account
  template:
    metadata:
      labels:
        app: mb-mjbl-account
    spec:
      #nodeName: c1ukubwkr03
      containers:
        - name: mb-mjbl-account
          image: 10.92.0.87:1521/uat/mb-mjbl-account:57082
          imagePullPolicy: IfNotPresent
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3

          ports:
            - containerPort: 8080
              name: app-port
          resources:
            requests:
              memory: "1Gi"
              #cpu: "1000m"
            limits:
              memory: "6Gi"
              #cpu: "2000m"

          env:
            # Database Configuration START
            - name: "DB_MB_HOST"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_MB_HOST
            - name: "DB_MB_PORT"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_MB_PORT
            - name: "DB_MB_DATABASE_NAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_MB_DATABASE_NAME
            - name: "DB_MB_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_MB_USERNAME
            - name: "DB_MB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_MB_PASSWORD

            - name: "DB_CORE_BANKING_HOST"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_CORE_BANKING_HOST
            - name: "DB_CORE_BANKING_PORT"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_CORE_BANKING_PORT
            - name: "DB_CORE_BANKING_DATABASE_NAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_CORE_BANKING_DATABASE_NAME
            - name: "DB_CORE_BANKING_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_CORE_BANKING_USERNAME
            - name: "DB_CORE_BANKING_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_CORE_BANKING_PASSWORD
            # Database Configuration END

            # Configuration Local Cluster START
            - name: "MS_CENTRALIZED_LOG_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-local-cluster-credentials
                  key: MS_CENTRALIZED_LOG_BASE_URL
            - name: "MS_MJBL_IN_HOUSE_API_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-local-cluster-credentials
                  key: MS_MJBL_IN_HOUSE_API_BASE_URL
            - name: "MS_MJBL_IN_HOUSE_CBS_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-local-cluster-credentials
                  key: MS_MJBL_IN_HOUSE_CBS_BASE_URL
            - name: "MS_COMMON_VALIDATION_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-local-cluster-credentials
                  key: MS_COMMON_VALIDATION_BASE_URL
            - name: "SPORTAL_WEB_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-local-cluster-credentials
                  key: SPORTAL_WEB_BASE_URL
            # Configuration Local Cluster END

            # Configuration Service START
            - name: "MS_MJBL_IN_HOUSE_API_KEY"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-service-credentials
                  key: MS_MJBL_IN_HOUSE_API_KEY
            - name: "MB_SECURITY_ENCRYPTION_KEY"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-service-credentials
                  key: MB_SECURITY_ENCRYPTION_KEY
            # Configuration Service END

            # Configuration Static Variable START
            - name: "IS_SENDING_REAL_OTP"
              value: "false"
            - name: "DUMMY_NUMBER_SENDING_OTP"
              value: "0"
            - name: "LOGGING_LEVEL"
              value: "DEBUG"
            # Configuration Static Variable END


          securityContext:
            allowPrivilegeEscalation: false
          
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - mb-mjbl-account
                topologyKey: "kubernetes.io/hostname"
              weight: 1
              

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-mobile-banking
  name: mb-mjbl-account-local
spec:
  type: ClusterIP
  selector:
    app: mb-mjbl-account
  ports:
    - port: 9008
      targetPort: app-port

