apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mjbl-external-kafka
  template:
    metadata:
      labels:
        app: mjbl-external-kafka
    spec:
      containers:
        - name: mjbl-external-kafka
          image: 10.92.0.87:1521/uat/apache/kafka:3.8.0
          ports:
            - containerPort: 9092
              name: app-port
            - containerPort: 9093
          volumeMounts:
            - name: mjbl-external-kafka-data
              mountPath: /var/lib/mjbl-external-kafka/data
            - name: mjbl-external-kafka-metadata
              mountPath: /var/lib/mjbl-external-kafka/metadata
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          securityContext:
              allowPrivilegeEscalation: false
      volumes:
        - name: mjbl-external-kafka-data
          emptyDir: {}
        - name: mjbl-external-kafka-metadata
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mjbl-external-kafka
                topologyKey: "kubernetes.io/hostname"
              weight: 1

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka
spec:
  type: NodePort
  selector:
    app: mjbl-external-kafka
  ports:
    - protocol: TCP
      port: 9026
      targetPort: app-port
      nodePort: 31004

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka-local
spec:
  type: ClusterIP
  selector:
    app: mjbl-external-kafka
  ports:
    - port: 9026
      targetPort: app-port

---

apiVersion: v1
kind: Service
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka-lb
spec:
  type: LoadBalancer
  selector:
    app: mjbl-external-kafka
  ports:
  - port: 31004
    targetPort: app-port
    protocol: TCP