---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mjbl-external-kafka
  template:
    metadata:
      labels:
        app: mjbl-external-kafka
    spec:
      containers:
      - name: mjbl-external-kafka
        image: 10.92.0.87:1521/uat/apache/kafka:3.8.0
        ports:
        - containerPort: 9026
        env:
        - name: KAFKA_KRAFT_MODE
          value: "true"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9026"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://mjbl-external-kafka:9026"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/mjbl-external-kafka/data"
        - name: KAFKA_KRAFT_MODE_BOOTSTRAP_SERVERS
          value: "mjbl-external-kafka:9026"
        volumeMounts:
        - name: mjbl-external-kafka-data
          mountPath: /var/lib/mjbl-external-kafka/data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: mjbl-external-kafka-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mjbl-external-kafka
  namespace: mjbl-api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 9026
    targetPort: 9026
  selector:
    app: mjbl-external-kafka

---
apiVersion: v1
kind: Service
metadata:
  name: mjbl-external-kafka-local
  namespace: mjbl-api-gateway
spec:
  ports:
  - port: 9026
    targetPort: 9026
  selector:
    app: mjbl-external-kafka
