apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mjbl-external-kafka
  template:
    metadata:
      labels:
        app: mjbl-external-kafka
    spec:
      containers:
      - name: mjbl-external-kafka
        image: 10.92.0.87:1521/uat/apache/kafka:3.8.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_KRAFT_MODE
          value: "true"
        - name: KAFKA_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"
        - name: KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE
          value: "false"
        - name: KAFKA_KRAFT_MODE
          value: "true"
        - name: KAFKA_KRAFT_MODE_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: kafka-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: mjbl-external-kafka

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka-local
spec:
  type: ClusterIP
  selector:
    app: mjbl-external-kafka
  ports:
    - port: 9026
      targetPort: app-port