---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mjbl-external-kafka
  template:
    metadata:
      labels:
        app: mjbl-external-kafka
    spec:
      containers:
      - name: mjbl-external-kafka
        image: 10.92.0.87:1521/uat/apache/kafka:3.8.0
        ports:
        - containerPort: 9092
          name: app-port
        volumeMounts:
        - name: mjbl-external-kafka-data
          mountPath: /var/lib/mjbl-external-kafka/data
        env:
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://mjbl-internal-kafka:9029"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/mjbl-internal-kafka/data"
        - name: KAFKA_BOOTSTRAP_SERVER
          value: "mjbl-internal-kafka:9092"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        securityContext:
            allowPrivilegeEscalation: false
      volumes:
      - name: mjbl-external-kafka-data
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mjbl-external-kafka
                topologyKey: "kubernetes.io/hostname"
              weight: 1

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka
spec:
  type: NodePort
  selector:
    app: mjbl-external-kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: app-port
      nodePort: 32099

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-kafka-local
spec:
  type: ClusterIP
  selector:
    app: mjbl-external-kafka
  ports:
    - port: 9026
      targetPort: app-port