apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-api-gateway
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mjbl-external-api-gateway
  template:
    metadata:
      labels:
        app: mjbl-external-api-gateway
    spec:
      nodeName: uat-api-gw-k8s-w2
      containers:
        - name: mjbl-external-api-gateway
          image: 10.92.0.87:1521/uat/mjbl-external-api-gateway:54426
          imagePullPolicy: IfNotPresent

          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3

          ports:
            - containerPort: 8080
              name: app-port
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "6Gi"
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: "INTERNAL_API_GATEWAY_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-service-credentials
                  key: INTERNAL_API_GATEWAY_BASE_URL
            - name: "INTERNAL_API_GATEWAY_IMAGE_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-service-credentials
                  key: INTERNAL_API_GATEWAY_BASE_URL
            - name: "KAKFA_HOST"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-service-credentials
                  key: KAKFA_HOST
            - name: "REDIS_HOST_NAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-service-credentials
                  key: REDIS_HOST_NAME
            - name: "REDIS_PORT_NUMBER"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-service-credentials
                  key: REDIS_PORT_NUMBER
            # Configuration Static Variable START
            - name: LOGGING_LEVEL
              value: "DEBUG"
            - name: "USER_TIMEZONE"
              value: "Asia/Bangkok"
            # Configuration Static Variable END
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mjbl-external-api-gateway
                topologyKey: "kubernetes.io/hostname"
              weight: 1

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-external-api-gateway
spec:
  type: NodePort
  selector:
    app: mjbl-external-api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: app-port
      nodePort: 30001
