apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-mobile-banking
  name: mjbl-kafka
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mjbl-kafka
  template:
    metadata:
      labels:
        app: mjbl-kafka
    spec:
      containers:
        - name: mjbl-kafka
          image: 10.92.0.87:1521/uat/apache/kafka:3.8.0
          ports:
            - containerPort: 9024
              name: app-port
          volumeMounts:
            - name: mjbl-kafka-data
              mountPath: /var/lib/mjbl-kafka/data
            - name: mjbl-kafka-metadata
              mountPath: /var/lib/mjbl-kafka/metadata
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "CONTROLLER://:9093,PLAINTEXT://:9024"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://mjbl-kafka-local.mjbl-mobile-banking.svc.cluster.local:9024"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
            - name: KAFKA_CFG_MESSAGE_MAX_BYTES
              value: "20971520"
            - name: KAFKA_CFG_REPLICA_FETCH_MAX_BYTES
              value: "20971520"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          securityContext:
              allowPrivilegeEscalation: false
      volumes:
        - name: mjbl-kafka-data
          emptyDir: {}
        - name: mjbl-kafka-metadata
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mjbl-kafka
                topologyKey: "kubernetes.io/hostname"
              weight: 1

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-mobile-banking
  name: mjbl-kafka-local
spec:
  type: ClusterIP
  selector:
    app: mjbl-kafka
  ports:
    - protocol: TCP
      port: 9024
      targetPort: app-port