version: '3.8'
services:
  kafka:
    image: 10.92.0.87:1521/uat/apache/kafka:3.8.0
    deploy:
      resources:
        reservations:
          cpus: "1"
          memory: 2G
        limits:
          cpus: "1"
          memory: 2G
    restart: on-failure
    container_name: kafka
    ports:
      - "9091:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: ""
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_INIT_KRAFT_MODE: "true"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "s-portal:1:1"
      KAFKA_CLUSTER_ID: "1"
    command: [ "sh", "-c", "/opt/kafka/bin/kafka-storage.sh format -t '1' -c /opt/kafka/config/kraft/server.properties && /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties" ]
    # volumes:
    #   - ./server.properties:/opt/kafka/config/kraft/server.properties

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-mobile-banking
  name: mjbl-kafka-local
spec:
  type: ClusterIP
  selector:
    app: mjbl-kafka
  ports:
    - port: 9024
      targetPort: 9092