apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-internal-centralized-logs-consumer
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mjbl-internal-centralized-logs-consumer
  template:
    metadata:
      labels:
        app: mjbl-internal-centralized-logs-consumer
    spec:
      containers:
        - name: mjbl-internal-centralized-logs-consumer
          image: 10.92.0.87:1521/uat/mjbl-internal-centralized-log-consumer:51686
          imagePullPolicy: IfNotPresent

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          ports:
            - containerPort: 8080
              name: app-port
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
          env:
            # Database Configuration START
            - name: "DB_MB_HOST"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: DB_MB_HOST
            - name: "DB_MB_PORT"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: DB_MB_PORT
            - name: "DB_MB_DATABASE_NAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: DB_MB_DATABASE_NAME
            - name: "DB_MB_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: DB_MB_USERNAME
            - name: "DB_MB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: DB_MB_PASSWORD
            # Database Configuration END
            - name: "KAFKA_HOST"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: KAFKA_HOST
            - name: "KAFKA_TOPIC_ODD_DAY"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: KAFKA_TOPIC_ODD_DAY
            - name: "KAFKA_TOPIC_EVEN_DAY"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: KAFKA_TOPIC_EVEN_DAY
            - name: "KAFKA_GROUP_ID"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: KAFKA_GROUP_ID
            - name: "KAFKA_CONSUMER_MAX_POOL_RECORDS"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: KAFKA_CONSUMER_MAX_POOL_RECORDS 

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mjbl-internal-centralized-logs-consumer
                topologyKey: "kubernetes.io/hostname"
              weight: 1
---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-internal-centralized-logs-consumer-local
spec:
  type: ClusterIP
  selector:
    app: mjbl-internal-centralized-logs-consumer
  ports:
    - port: 9025
      targetPort: app-port
