apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-mobile-banking
  name: mjbl-internal-microservice-account
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mjbl-internal-microservice-account
  template:
    metadata:
      labels:
        app: mjbl-internal-microservice-account
    spec:
      #nodeName: c1ukubwkr03
      containers:
        - name: mjbl-internal-microservice-account
          image: 10.92.0.87:1521/uat/mjbl-internal-microservice-account:54504
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          ports:
            - containerPort: 8080
              name: app-port
          resources:
            requests:
              memory: "256Mi"
              #cpu: "1000m"
            limits:
              memory: "512Mi"
              #cpu: "2000m"

          env:
            # Database Configuration START
            - name: "DB_CORE_BANKING_HOST"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_CORE_BANKING_HOST
            - name: "DB_CORE_BANKING_PORT"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_CORE_BANKING_PORT
            - name: "DB_CORE_BANKING_DATABASE_NAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_CORE_BANKING_DATABASE_NAME
            - name: "DB_CORE_BANKING_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_CORE_BANKING_USERNAME
            - name: "DB_CORE_BANKING_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-db-credentials
                  key: DB_CORE_BANKING_PASSWORD
            # Database Configuration END

            # Configuration static variable START
            - name: "LOGGING_LEVEL"
              value: "DEBUG"
            - name: "GET_ENTRY_REF_MAX_LOOP"
              value: "20"
            # Configuration static variable END
          securityContext:
            allowPrivilegeEscalation: false
          
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - mjbl-internal-microservice-account
                topologyKey: "kubernetes.io/hostname"
              weight: 1

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-mobile-banking
  name: mjbl-internal-microservice-account-local
spec:
  type: ClusterIP
  selector:
    app: mjbl-internal-microservice-account
  ports:
    - port: 9010
      targetPort: app-port

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-mobile-banking
  name: mjbl-internal-microservice-account
spec:
  type: NodePort
  selector:
    app: mjbl-internal-microservice-account
  ports:
    - protocol: TCP
      port: 8080
      targetPort: app-port
      nodePort: 30004
