apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-mobile-banking
  name: mb-mjbl-limitation-validation
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mb-mjbl-limitation-validation
  template:
    metadata:
      labels:
        app: mb-mjbl-limitation-validation
    spec:
      #nodeName: c1ukubwkr03
      containers:
        - name: mb-mjbl-limitation-validation
          image: 10.92.0.87:1521/uat/mb-mjbl-limitation-validation:50555
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          ports:
            - containerPort: 8080
              name: app-port
          resources:
            requests:
              memory: "256Mi"
              #cpu: "1000m"
            limits:
              memory: "512Mi"
              #cpu: "2000m"

          env:
            # Configuration Service START
            - name: "HASH_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-service-credentials
                  key: HASH_SECRET_KEY
            # Configuration Service END

          securityContext:
            allowPrivilegeEscalation: false
          
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - mb-mjbl-limitation-validation
                topologyKey: "kubernetes.io/hostname"
              weight: 1

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-mobile-banking
  name: mb-mjbl-limitation-validation-local
spec:
  type: ClusterIP
  selector:
    app: mb-mjbl-limitation-validation
  ports:
    - port: 9010
      targetPort: app-port
