apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-internal-api-gateway
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mjbl-internal-api-gateway
  template:
    metadata:
      labels:
        app: mjbl-internal-api-gateway
    spec:
      containers:
        - name: mjbl-internal-api-gateway
          image: 10.92.0.87:1521/uat/mjbl-internal-api-gateway:51722
          imagePullPolicy: IfNotPresent

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          ports:
            - containerPort: 8080
              name: app-port
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: "DB_MB_HOST"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-db-credentials
                  key: DB_MB_HOST
            - name: "DB_MB_PORT"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-db-credentials
                  key: DB_MB_PORT
            - name: "DB_MB_DATABASE_NAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-db-credentials
                  key: DB_MB_DATABASE_NAME
            - name: "DB_MB_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-db-credentials
                  key: DB_MB_USERNAME
            - name: "DB_MB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-db-credentials
                  key: DB_MB_PASSWORD
            # Local Cluster Config START
            - name: "MS_CENTRALIZED_LOG_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: MS_CENTRALIZED_LOG_BASE_URL
            - name: "MS_GATEWAY_CONFIG_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: MS_GATEWAY_CONFIG_BASE_URL
            - name: "REDIS_HOST_NAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: REDIS_HOST_NAME
            - name: "REDIS_PORT_NUMBER"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: REDIS_PORT_NUMBER
            - name: "KAFKA_HOST"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: KAFKA_HOST
            - name: "KAFKA_TOPIC_ODD_DAY"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: KAFKA_TOPIC_ODD_DAY
            - name: "KAFKA_TOPIC_EVEN_DAY"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: KAFKA_TOPIC_EVEN_DAY
            - name: "KAFKA_GROUP_ID"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: KAFKA_GROUP_ID
            - name: "KAFKA_CONSUMER_MAX_POOL_RECORDS"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-local-cluster-credentials
                  key: KAFKA_CONSUMER_MAX_POOL_RECORDS      
            # Local Cluster Config END 

            # Service Configuration START
            - name: "GATEWAY_API_KEY"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-service-credentials
                  key: GATEWAY_API_KEY
            - name: "GATEWAY_IP_WHITELIST"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-service-credentials
                  key: GATEWAY_IP_WHITELIST
            - name: "REDIS_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-service-credentials
                  key: REDIS_USERNAME
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mjbl-api-gateway-service-credentials
                  key: REDIS_PASSWORD

            # Service Configuration END
          securityContext:
            allowPrivilegeEscalation: false

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mjbl-internal-api-gateway
                topologyKey: "kubernetes.io/hostname"
              weight: 1

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-internal-api-gateway
spec:
  type: NodePort
  selector:
    app: mjbl-internal-api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: app-port
      nodePort: 30001