apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-internal-microservice
  name: mjbl-internal-api-gateway
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mjbl-internal-api-gateway
  template:
    metadata:
      labels:
        app: mjbl-internal-api-gateway
    spec:
      containers:
        - name: mjbl-internal-api-gateway
          image: 10.92.0.87:1521/uat/mjbl-api-gateway-configuration-service:49859
          imagePullPolicy: IfNotPresent

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          ports:
            - containerPort: 8080
              name: app-port
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: "DB_MB_HOST"
              valueFrom:
                secretKeyRef:
                  name: mjbl-internal-microservice-db-credentials
                  key: DB_MB_HOST
            - name: "DB_MB_PORT"
              valueFrom:
                secretKeyRef:
                  name: mjbl-internal-microservice-db-credentials
                  key: DB_MB_PORT
            - name: "DB_MB_DATABASE_NAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-internal-microservice-db-credentials
                  key: DB_MB_DATABASE_NAME
            - name: "DB_MB_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: mjbl-internal-microservice-db-credentials
                  key: DB_MB_USERNAME
            - name: "DB_MB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: mjbl-internal-microservice-db-credentials
                  key: DB_MB_PASSWORD

          securityContext:
            allowPrivilegeEscalation: false

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mjbl-internal-api-gateway
                topologyKey: "kubernetes.io/hostname"
              weight: 1

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-internal-microservice
  name: mjbl-internal-api-gateway
spec:
  type: NodePort
  selector:
    app: mjbl-internal-api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: app-port
      nodePort: 32001

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-internal-microservice
  name: mjbl-internal-api-gateway-local
spec:
  type: ClusterIP
  selector:
    app: mjbl-internal-api-gateway
  ports:
    - port: 9001
      targetPort: app-port
