apiVersion: v1
kind: Secret
metadata:
  name: mjbl-mb-local-cluster-credentials
  namespace: mjbl-mobile-banking
type: Opaque
data:
  MS_IDENTIFICATION_BASE_URL: aHR0cDovL21iLW1qYmwtaWRlbnRpZmljYXRpb24tbG9jYWwubWpibC1tb2JpbGUtYmFua2luZy5zdmMuY2x1c3Rlci5sb2NhbDo5MDA1
  MS_HASH_VALIDATION_BASE_URL: aHR0cDovL21iLW1qYmwtaGFzaC12YWxpZGF0aW9uLWxvY2FsLm1qYmwtbW9iaWxlLWJhbmtpbmcuc3ZjLmNsdXN0ZXIubG9jYWw6OTAwNg==
  MS_LIMITATION_VALIDATION_BASE_URL: aHR0cDovL21iLW1qYmwtbGltaXRhdGlvbi12YWxpZGF0aW9uLWxvY2FsLm1qYmwtbW9iaWxlLWJhbmtpbmcuc3ZjLmNsdXN0ZXIubG9jYWw6OTAwNw==
  MS_COMMON_VALIDATION_BASE_URL: aHR0cDovL21iLW1qYmwtY29tbW9uLXZhbGlkYXRpb24tbG9jYWwubWpibC1tb2JpbGUtYmFua2luZy5zdmMuY2x1c3Rlci5sb2NhbDo5MDAz
  MS_MJBL_IN_HOUSE_API_BASE_URL: MTkyLjE2OC4xLjYxOjQ0MzM2
  MS_CENTRALIZED_LOG_BASE_URL: aHR0cDovLzE3Mi4xNy4yNTEuNTM6MzAwNzg=
  MS_OTP_BASE_URL: aHR0cDovLzE3Mi4xNy4yNTEuNTI6MzAwMjA=
