apiVersion: v1
kind: Secret
metadata:
  name: mjbl-api-gateway-service-credentials
  namespace: mjbl-api-gateway
type: Opaque
data:
  # Internal API Gateway START
  GATEWAY_API_KEY: Z2F0ZXdheS1hcGkta2V5
  GATEWAY_IP_WHITELIST: MTAuOTIuMC44MiwxMC45My4wLjI0
  REDIS_USERNAME: ZGVmYXVsdA==
  REDIS_PASSWORD: U3BuQDEyMzQ=
  # Internal API Gateway END