apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mjbl-mobile-banking
  name: mb-mjbl-other-bank-transfer
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: mb-mjbl-other-bank-transfer
  template:
    metadata:
      labels:
        app: mb-mjbl-other-bank-transfer
    spec:
      #nodeName: c1ukubwkr03
      containers:
        - name: mb-mjbl-other-bank-transfer
          image: 10.92.0.87:1521/uat/mb-mjbl-other-bank-transfer:55722
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          ports:
            - containerPort: 8080
              name: app-port
          resources:
            requests:
              memory: "256Mi"
              #cpu: "1000m"
            limits:
              memory: "512Mi"
              #cpu: "2000m"

          env:

            # Configuration Local Cluster START
            - name: "MS_MJBL_IN_HOUSE_CBS_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-local-cluster-credentials
                  key: MS_MJBL_IN_HOUSE_CBS_BASE_URL
                  
            - name: "MS_COMMON_VALIDATION_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-local-cluster-credentials
                  key: MS_COMMON_VALIDATION_BASE_URL
            - name: "MS_CENTRALIZED_LOG_BASE_URL"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-local-cluster-credentials
                  key: MS_CENTRALIZED_LOG_BASE_URL
            # Configuration Local Cluster END

            # Configuration Service START
            - name: "MS_MJBL_IN_HOUSE_API_KEY"
              valueFrom:
                secretKeyRef:
                  name: mjbl-mb-service-credentials
                  key: MS_MJBL_IN_HOUSE_API_KEY
            # Configuration Service END

          securityContext:
            allowPrivilegeEscalation: false
          
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - mb-mjbl-other-bank-transfer
                topologyKey: "kubernetes.io/hostname"
              weight: 1
              

---

kind: Service
apiVersion: v1
metadata:
  namespace: mjbl-mobile-banking
  name: mb-mjbl-other-bank-transfer-local
spec:
  type: ClusterIP
  selector:
    app: mb-mjbl-other-bank-transfer
  ports:
    - port: 9015
      targetPort: app-port
